### ISSUE TITLE
jupyter notebook igv, doubleClickDelay=1 does not disable "double click to zoom"

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js-jupyter#6]
This solution used to (probably still does) work in igv.js.
My tests and experiments lead me to believe it does not work for the notebook widget.

The first few lines of my call to the constructor:

    igv = IGV(locus="chr21:25,863,045-25,887,052", 
          reference=Reference(id="hg38"), 
          doubleClickDelay=1,
          tracks=[Track(
                   name="Genes hg38 v24",
                   ....

**Comment by jrobinso** [comment]
@paul-shannon could you refresh our memory a little on what you are trying to accomplish,  and what is happening in jupyter to lead you to believe it is failing?    IIRC you are basically trying to turn double-click zoom off.

**Comment by paul-shannon** [comment]
Hi Jim,

Yes, you are exactly right:  I want to turn off double-click zoom in igv.js-jupyter.  

What I see now is that, no matter what value very small or zero value I assign to doubleClickDelay, the double-click zoom still happens.

 - Paul

**Comment by turner** [comment]
I am looking at this now.

**Comment by turner** [comment]
I deployed a new test version to PyPi Test that should fix the double-click issue.

**Comment by paul-shannon** [comment]
Hi Douglass,

Thanks very much for fixing the double-click issue.  I am new to PyPi - will the fix perhaps be available from github also, maybe on a dev branch?

Thanks,

 - Paul

**Comment by turner** [comment]
Paul, yes. Just clone master or download as a zip file.

**Comment by paul-shannon** [comment]
just cloned master,  pip installed, installed and enabled the extension.   Will be happy to discover that the error is mine, but I still cannot disable the double-click-zoom.   Here is my simple test, after which double-click on the canvas triggers a zoom:

    igv = IGV(locus="chr1:1-200", reference=Reference(id="hg19"), 
          tracks=[Track(
                   name="Genes", 
                   doubleClickDelay=1,
                   url="//s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed",
                   index_url="//s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed.idx", 
                   display_mode="EXPANDED")])

**Comment by tmtabor** [comment]
I believe the below code should work (note the change on line 4).

```python
igv = IGV(locus="chr1:1-200", reference=Reference(id="hg19"), 
          tracks=[Track(
                   name="Genes", 
                   double_click_delay=1,
                   url="//s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed",
                   index_url="//s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed.idx", 
                   display_mode="EXPANDED")])

**Comment by paul-shannon** [comment]
After substituting your code in the notebook: alas, still no.   

I appear to be using the correct version of the extension:

  [D 11:28:24.003 NotebookApp] 200 GET /nbextensions/igv/igvjs/igv-1.0.1.min.js?v=20160930112807 (::1) 5.06ms

Anything else I can try?

Thanks!

 - Paul

**Comment by tmtabor** [comment]
I apologize. There was a typo in my code before. I've since fixed it. Namely, double_click_delay is a parameter on the IGV object, rather than the Track object.

**Comment by paul-shannon** [comment]
The fix works perfectly.  Thank you!
